### PR TITLE
Update dependencies for xcode 11.4 use

### PR DESCRIPTION
**Pull request by ZuBlomberg**
I updated the dependencies so we can use and build it in Xcode 11.4 and higher.

@dennispost @lightsprint09 @philippseibel

### CODE REVIEW

**Comment by lightsprint09** [comment]
Looks. Good. Just wait if Travis builds it.

Maybe you need to upgrade travis  Xcode version as well.

**Comment by lightsprint09** [comment]
have a look at https://travis-ci.org/github/dbsystel/DBNetworkStack-Sourcing

I think you need ro remove tvOS support because it got removed in Sourcing as well.

And you need to define a new Watch OS simulator for testing

**Comment by ZuBlomberg** [comment]
The project always uses the frameworks under Carthage/Build/iOS/.. So every time it's building for tvOS and watchOS it is using the iOS frameworks of Sourcing and DBNetworkStack and the build fails. Sadly I have no idea how to fix this issue.

**Comment by ZuBlomberg** [comment]
@lightsprint09 I could solve the problems with building and testing and now travis is running without any problems. Now everything is ready for merging.

**Comment by lightsprint09** [comment]
@ZuBlomberg Thats nice. Everything is looking good now. I will merge once Travis finished building.

**Comment by ZuBlomberg** [comment]
@lightsprint09 Travis ran already successfully (see here: https://travis-ci.org/github/dbsystel/DBNetworkStack-Sourcing/builds/690913874) but GitHub gets no response from travis.
I think that could be the reason why its stuck on "Waiting for status ..": https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

Can the PR be merged manually without a automatic response from travis or must this be fixed first?

**Pull request merged**
